name: Build and Deploy Preview
on:
  push:
    branches:
      - master
      - author/**
  pull_request:
    branches:
      - master
      - author/**

jobs:
  publish:
    runs-on: macos-10.15
    steps:
    - name: Swift setup
      uses: YOCKOW/Action-setup-swift@v1.1.2
      with:
        swift-version: 5.2

    - name: Publish setup
      run: |
        git clone https://github.com/JohnSundell/Publish.git
        cd Publish
        make

    - uses: actions/checkout@v2
    
    - name: Build Output folder
      run: |
        publish generate
    
    - name: Get current date
      id: date
      run: |
        echo "::set-output name=date::$(date +'%Y-%m-%d %H:%M')"
    
    - name: Install SSH Client 🔑
      uses: webfactory/ssh-agent@v0.2.0 # This step installs the ssh client into the workflow run. There's many options available for this on the action marketplace.
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}
      
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@3.4.8
      with:
        SSH: true
        BASE_BRANCH: master
        BRANCH: master
        FOLDER: Output
        COMMIT_MESSAGE: "Deployment ${{ steps.date.outputs.date }}: ${{ github.event.head_commit.message }}"
        REPOSITORY_NAME: abrampers/abrampers.github.io
        SINGLE_COMMIT: false
