name: Publish
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  publish:
    runs-on: macos-10.15
    steps:
    - name: Swift setup
      uses: YOCKOW/Action-setup-swift@v1.1.2
      with:
        swift-version: 5.1

    - name: Publish setup
      run: |
        git clone https://github.com/JohnSundell/Publish.git
        cd Publish
        make

    - uses: actions/checkout@v2
      
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v1.4.0
      with:
        # GitHub repository where assets will be deployed (default current)
        repo: abrampers/abrampers.github.io
        # Git branch where assets will be deployed
        target_branch: master
        # Create incremental commit instead of doing push force
        keep_history: false
        # Build directory to deploy
        build_dir: ./Output
        # Commit author's name
        committer_name: Abram Situmorang
        # Commit author's email
        committer_email: abram.perdanaputra@gmail.com
        # Commit message
        commit_message: Deployment
        # Write the given domain name to the CNAME file
        fqdn: abram.id
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
