name: Publish
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  publish:
    runs-on: macos-10.15
    steps:
    - name: Swift setup
      uses: YOCKOW/Action-setup-swift@v1.1.2
      with:
        swift-version: 5.1

    - name: Publish setup
      run: |
        git clone https://github.com/JohnSundell/Publish.git
        cd Publish
        make

    - uses: actions/checkout@v2
    
    - name: Build Output folder
      run: |
        publish generate
    
    - name: Get current date
      id: date
      run: |
        echo "::set-output name=date::$(date +'%Y-%m-%d')"
        pwd
      
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@3.4.8
      with:
        SSH: false
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: master
        FOLDER: Output
        COMMIT_MESSAGE: Deployment ${{steps.date.outputs.date}}
        REPOSITORY_NAME: abrampers/abrampers.github.io
        SINGLE_COMMIT: false
      env:
        ACTIONS_STEP_DEBUG: true
